// Package genphp emits the PHP side of the encx bindings: the Client class
// wrapping the opaque Go handle, and the Helpers class holding the
// package-level functions that need no client.
//
// The output is a pure function of the surface model. Nothing is read from the
// environment, no map is iterated, and no timestamp or file path reaches the
// generated text, so the same model always produces the same bytes and a
// freshly generated file can be diffed against the committed one.
package genphp

import (
	"fmt"
	"slices"
	"strings"

	"github.com/skrashevich/encx-cli/bindings/php/internal/surface"
)

const (
	// generatedMarker is the line every consumer greps for before editing.
	generatedMarker = "// Code generated by encxphpgen. DO NOT EDIT."
	// indent is one level of PHP indentation.
	indent = "    "
	// lineBudget is the column past which a parameter list or an argument
	// list is broken onto its own lines.
	lineBudget = 100
	// freeCName releases a client handle on the Go side. It is not part of
	// the bound surface: it belongs to the handle registry, not to
	// encxmobile.
	freeCName = "encx_client_free"
)

// clientReserved are the members Client always declares, generated or not.
// A bound method that lowers onto one of these names would silently replace
// it, so the emitter refuses instead.
var clientReserved = []string{"__construct", "__destruct", "close", "handle"}

// ClientFile returns the contents of bindings/php/src/Encx/Client.php.
func ClientFile(m *surface.Model) ([]byte, error) {
	ctors := sortedByPHPName(m.Constructors)
	methods := sortedByPHPName(m.Methods)

	all := make([]surface.Func, 0, len(ctors)+len(methods))
	all = append(all, ctors...)
	all = append(all, methods...)
	if err := ensureUnique("Client", all, clientReserved); err != nil {
		return nil, err
	}

	members := []string{fmt.Sprintf(clientScaffold, freeCName)}
	for _, f := range ctors {
		member, err := renderMethod(f, true, false)
		if err != nil {
			return nil, fmt.Errorf("genphp: Client::%s: %w", MethodName(f.Name), err)
		}
		members = append(members, member)
	}
	for _, f := range methods {
		member, err := renderMethod(f, false, true)
		if err != nil {
			return nil, fmt.Errorf("genphp: Client::%s: %w", MethodName(f.Name), err)
		}
		members = append(members, member)
	}

	var b strings.Builder
	writeHeader(&b)
	b.WriteString(clientClassDoc)
	b.WriteString("final class Client\n{\n")
	b.WriteString(strings.Join(members, "\n"))
	b.WriteString("}\n")
	return []byte(b.String()), nil
}

// HelpersFile returns the contents of bindings/php/src/Encx/Helpers.php.
//
// The file is emitted even when the model binds no package-level function, so
// that the set of generated files does not depend on the package contents.
func HelpersFile(m *surface.Model) ([]byte, error) {
	funcs := sortedByPHPName(m.Functions)
	if err := ensureUnique("Helpers", funcs, nil); err != nil {
		return nil, err
	}

	var members []string
	for _, f := range funcs {
		member, err := renderMethod(f, true, false)
		if err != nil {
			return nil, fmt.Errorf("genphp: Helpers::%s: %w", MethodName(f.Name), err)
		}
		members = append(members, member)
	}

	var b strings.Builder
	writeHeader(&b)
	b.WriteString(helpersClassDoc)
	b.WriteString("final class Helpers\n{\n")
	if len(members) == 0 {
		b.WriteString(indent + "// The bound package exports no client-free function, so this class is\n")
		b.WriteString(indent + "// empty. It is emitted anyway to keep the generated file set fixed.\n")
	} else {
		b.WriteString(strings.Join(members, "\n"))
	}
	b.WriteString("}\n")
	return []byte(b.String()), nil
}

func writeHeader(b *strings.Builder) {
	b.WriteString("<?php\n\n")
	b.WriteString(generatedMarker + "\n\n")
	b.WriteString("declare(strict_types=1);\n\n")
	b.WriteString("namespace Encx;\n\n")
}

// sortedByPHPName copies fs into PHP method-name order, so that the generated
// class reads alphabetically rather than in Go's capital-first order.
func sortedByPHPName(fs []surface.Func) []surface.Func {
	out := slices.Clone(fs)
	slices.SortStableFunc(out, func(a, b surface.Func) int {
		return strings.Compare(MethodName(a.Name), MethodName(b.Name))
	})
	return out
}

// ensureUnique rejects two Go names that lower onto the same PHP method.
// PHP method names are case-insensitive, so the comparison is too.
func ensureUnique(class string, fs []surface.Func, reserved []string) error {
	seen := make(map[string]string, len(fs)+len(reserved))
	for _, name := range reserved {
		seen[strings.ToLower(name)] = name
	}
	for _, f := range fs {
		php := MethodName(f.Name)
		key := strings.ToLower(php)
		if prev, ok := seen[key]; ok {
			return fmt.Errorf("genphp: %s::%s collides with %s", class, php, prev)
		}
		seen[key] = f.Name
	}
	return nil
}

// renderMethod emits one method, including its PHPDoc block and a trailing
// newline. static drops the $this receiver; handle prepends $this->handle() as
// the first C argument, which every method bound to the client needs.
func renderMethod(f surface.Func, static, handle bool) (string, error) {
	ret, err := returnType(f.Result)
	if err != nil {
		return "", err
	}
	params, err := paramList(f.Params)
	if err != nil {
		return "", err
	}
	args, err := callArgs(f, handle)
	if err != nil {
		return "", err
	}

	var tags []string
	if f.Result.Kind == surface.KindJSONStruct {
		tags = append(tags, "@return array<string, mixed>")
	}
	// Every bound call travels through Ffi::call, which turns a failed
	// envelope into an exception, so every method can throw.
	tags = append(tags, "@throws EncxException")

	var b strings.Builder
	writeDoc(&b, f.Doc, tags)
	writeSignature(&b, MethodName(f.Name), params, ret, static)
	writeBody(&b, f.CName, args, f.Result)
	b.WriteString(indent + "}\n")
	return b.String(), nil
}

// writeDoc emits a PHPDoc block at one indentation level.
func writeDoc(b *strings.Builder, doc string, tags []string) {
	b.WriteString(indent + "/**\n")
	if doc != "" {
		for _, line := range strings.Split(doc, "\n") {
			// A doc comment that contained */ would close the block early.
			line = strings.ReplaceAll(line, "*/", "* /")
			b.WriteString(strings.TrimRight(indent+" * "+line, " "))
			b.WriteString("\n")
		}
		if len(tags) > 0 {
			b.WriteString(indent + " *\n")
		}
	}
	for _, tag := range tags {
		b.WriteString(indent + " * " + tag + "\n")
	}
	b.WriteString(indent + " */\n")
}

// writeSignature emits the declaration line and the opening brace, breaking a
// long parameter list across lines.
func writeSignature(b *strings.Builder, name string, params []string, ret string, static bool) {
	prefix := indent + "public "
	if static {
		prefix += "static "
	}
	prefix += "function " + name + "("
	suffix := "): " + ret

	oneLine := prefix + strings.Join(params, ", ") + suffix
	if len(oneLine) <= lineBudget {
		b.WriteString(oneLine + "\n" + indent + "{\n")
		return
	}

	b.WriteString(prefix + "\n")
	for _, p := range params {
		b.WriteString(indent + indent + p + ",\n")
	}
	b.WriteString(indent + suffix + " {\n")
}

// writeBody emits the single statement that forwards to the shared library,
// breaking a long argument list across lines.
func writeBody(b *strings.Builder, cName string, args []string, result surface.Result) {
	before, after := resultWrapper(result)
	body := indent + indent
	prefix := "Ffi::call('" + cName + "', ["
	suffix := "])"

	oneLine := body + before + prefix + strings.Join(args, ", ") + suffix + after + ";"
	if len(oneLine) <= lineBudget {
		b.WriteString(oneLine + "\n")
		return
	}

	b.WriteString(body + before + prefix + "\n")
	for _, a := range args {
		b.WriteString(body + indent + a + ",\n")
	}
	b.WriteString(body + suffix + after + ";\n")
}

// resultWrapper returns the text placed around the Ffi::call expression to
// turn the envelope value into the declared return type.
func resultWrapper(r surface.Result) (before, after string) {
	switch r.Kind {
	case surface.KindVoid, surface.KindError:
		return "", ""
	case surface.KindJSONStruct:
		return "return (array) ", ""
	case surface.KindHandle:
		return "return new self((int) ", ")"
	default:
		switch r.Type {
		case surface.TypeInt64:
			return "return (int) ", ""
		case surface.TypeBool:
			return "return (bool) ", ""
		case surface.TypeBytes:
			return "return Ffi::decodeBytes(", ")"
		default:
			return "return (string) ", ""
		}
	}
}

// returnType maps a Go result onto the declared PHP return type.
func returnType(r surface.Result) (string, error) {
	switch r.Kind {
	case surface.KindVoid, surface.KindError:
		return "void", nil
	case surface.KindJSONStruct:
		return "array", nil
	case surface.KindHandle:
		return "self", nil
	case surface.KindValue, surface.KindValueErr:
		switch r.Type {
		case surface.TypeString, surface.TypeBytes:
			return "string", nil
		case surface.TypeInt64:
			return "int", nil
		case surface.TypeBool:
			return "bool", nil
		}
		return "", fmt.Errorf("result type %s has no PHP mapping", r.Type)
	}
	return "", fmt.Errorf("result kind %s has no PHP mapping", r.Kind)
}

// paramList maps the Go parameters onto typed PHP parameters. A []byte
// parameter stays a single PHP string; it is the C call that splits into a
// pointer and a length.
func paramList(params []surface.Param) ([]string, error) {
	out := make([]string, 0, len(params))
	for _, p := range params {
		var php string
		switch p.Type {
		case surface.TypeString, surface.TypeBytes:
			php = "string"
		case surface.TypeInt64:
			php = "int"
		case surface.TypeBool:
			php = "bool"
		default:
			return nil, fmt.Errorf("parameter %q has type %s, which has no PHP mapping", p.Name, p.Type)
		}
		out = append(out, php+" $"+p.Name)
	}
	return out, nil
}

// callArgs builds the argument list handed to Ffi::call. Its order and length
// must match the exported C prototype, which is why a []byte parameter
// contributes two arguments and a bool is narrowed to an int.
func callArgs(f surface.Func, handle bool) ([]string, error) {
	out := make([]string, 0, len(f.Params)+1)
	if handle {
		out = append(out, "$this->handle()")
	}
	for _, p := range f.Params {
		v := "$" + p.Name
		switch p.Type {
		case surface.TypeString, surface.TypeInt64:
			out = append(out, v)
		case surface.TypeBool:
			out = append(out, v+" ? 1 : 0")
		case surface.TypeBytes:
			out = append(out, v, "strlen("+v+")")
		default:
			return nil, fmt.Errorf("parameter %q has type %s, which has no PHP mapping", p.Name, p.Type)
		}
	}
	return out, nil
}

const clientClassDoc = `/**
 * A live Encounter client backed by the encx shared library.
 *
 * An instance owns one handle into the Go side, so it is created through the
 * static factories below rather than with new. Release it with close() when the
 * work is done; the destructor does the same for a client that outlives its
 * last use.
 */
`

const helpersClassDoc = `/**
 * The encx package-level functions, which need no client and hold no state.
 */
`

// clientScaffold is the fixed part of Client: the handle it owns and its
// lifetime. %s is the C symbol that frees a handle.
const clientScaffold = indent + `/** The live handle into the Go client registry, or null once closed. */
    private ?int $handle;

    private function __construct(int $handle)
    {
        $this->handle = $handle;
    }

    /**
     * Frees the Go client for an instance that was never closed explicitly.
     *
     * A destructor must not let an exception escape, since PHP turns that into
     * a fatal error during shutdown; a failure here is therefore swallowed.
     * Call close() instead when the outcome matters.
     *
     * PHP forbids a return type on __destruct, so this signature has none.
     */
    public function __destruct()
    {
        try {
            $this->close();
        } catch (EncxException) {
            // Nothing left to report once the object is being destroyed.
        }
    }

    /**
     * Releases the Go client behind this instance.
     *
     * The handle is cleared before the call, so a second close() — including
     * the one from the destructor — does nothing and frees nothing twice.
     *
     * @throws EncxException
     */
    public function close(): void
    {
        $handle = $this->handle;
        if ($handle === null) {
            return;
        }

        $this->handle = null;
        Ffi::call('%s', [$handle]);
    }

    /**
     * Returns the handle this instance still owns.
     *
     * @throws EncxException when the client has already been closed
     */
    private function handle(): int
    {
        if ($this->handle === null) {
            throw new EncxException('the encx client is closed');
        }

        return $this->handle;
    }
`
