// Code generated by encxphpgen. DO NOT EDIT.
//
// C ABI of the encx PHP bindings, read by PHP through FFI::cdef.
//
// FFI::cdef runs no preprocessor and understands no typedefs it was not given,
// so this file holds nothing but prototypes and comments, and uses no type
// beyond char, int, long long, void and pointers to them.
//
// Every function returning char * hands ownership of that string to the caller:
// it is a malloc'd JSON envelope that must be released with encx_string_free.
// Methods take the opaque client handle produced by a constructor as their
// first argument; the handle is released with encx_client_free.

// Releases the client behind handle and returns an envelope. Handles are
// never reused, so freeing an already freed handle fails with an error
// envelope instead of releasing an unrelated client.
char *encx_client_free(long long handle);

// Frees a string returned by any other encx_ function. Passing a null
// pointer is a no-op.
void encx_string_free(char *s);

// NewClient creates an Encounter API client for the given domain.
// Set insecureTLS to true to skip TLS certificate verification (e.g. for tech.en.cx).
char *encx_new_client(char *domain, int insecure_tls);

// NewClientWithOptions creates a client with extended configuration.
// timeoutSeconds: HTTP client timeout (0 = default 15s). lang: API language (empty = "ru").
char *encx_new_client_with_options(char *domain, int insecure_tls, int use_http, long long timeout_seconds, char *lang);

// AcceptTeamInvitation accepts a team invitation.
char *encx_client_accept_team_invitation(long long handle, long long team_id);

// APIBaseURL returns the host the new engine is reached at.
char *encx_client_api_base_url(long long handle);

// ClearHAR removes all captured HAR entries.
char *encx_client_clear_har(long long handle);

// ClearHARFirst removes the n oldest captured HAR entries.
char *encx_client_clear_har_first(long long handle, long long n);

// Domain returns the configured Encounter domain.
char *encx_client_domain(long long handle);

// Engine reports which backend is actually serving this client.
char *encx_client_engine(long long handle);

// EnterGame registers the player in a game. Returns raw server response.
char *encx_client_enter_game(long long handle, long long game_id);

// ExportCookies serializes session cookies to JSON bytes for persistent storage.
char *encx_client_export_cookies(long long handle);

// ExportHAR returns captured traffic as a HAR 1.2 JSON document.
char *encx_client_export_har(long long handle);

// ExportHARSnapshot atomically exports captured traffic together with its
// entry count; pass the count to ClearHARFirst after a successful upload so
// entries captured during the upload are preserved.
char *encx_client_export_har_snapshot(long long handle);

// GetDomainGames returns games parsed from the domain main page as JSON array.
char *encx_client_get_domain_games(long long handle);

// GetGameDetails returns the game details page HTML.
char *encx_client_get_game_details(long long handle, long long game_id);

// GetGameList returns ComingGames and ActiveGames as JSON. page is 1-based (0 = first page).
char *encx_client_get_game_list(long long handle, long long page);

// GetGameModel returns the current game state as GameModel JSON.
char *encx_client_get_game_model(long long handle, long long game_id);

// GetGameModelLevel returns the state for a specific level number in storm sequence games.
char *encx_client_get_game_model_level(long long handle, long long game_id, long long level_number);

// GetGameStatistics returns full game statistics as JSON.
char *encx_client_get_game_statistics(long long handle, long long game_id);

// GetMyTeamDetails returns the current user's team page HTML.
char *encx_client_get_my_team_details(long long handle);

// GetPenaltyHint requests a penalty hint. Returns updated GameModel JSON.
char *encx_client_get_penalty_hint(long long handle, long long game_id, long long penalty_id);

// GetProfile returns the current user profile as JSON.
char *encx_client_get_profile(long long handle);

// GetTeamDetails returns team details page HTML.
char *encx_client_get_team_details(long long handle, long long team_id);

// GetTeamInvitations returns team invitations addressed to the current user as JSON.
char *encx_client_get_team_invitations(long long handle);

// GetTeamManagementInfo returns parsed team management info as JSON.
char *encx_client_get_team_management_info(long long handle, long long team_id);

// GetTimeoutToGame returns seconds until game start, or -1 if no counter is present.
char *encx_client_get_timeout_to_game(long long handle, long long game_id);

// HAREntryCount returns the number of captured HAR entries.
char *encx_client_har_entry_count(long long handle);

// ImportCookies restores session cookies from JSON bytes produced by ExportCookies.
char *encx_client_import_cookies(long long handle, char *data, long long data_len);

// InviteTeamMember invites a user login into a team.
char *encx_client_invite_team_member(long long handle, long long team_id, char *login);

// LeaveTeam leaves a team when TeamDetails.aspx exposes a leave action.
char *encx_client_leave_team(long long handle, long long team_id);

// Login authenticates on the Encounter domain. Returns LoginResponse JSON.
char *encx_client_login(long long handle, char *login, char *password);

// LoginWithCaptcha authenticates with CAPTCHA digits when Login returns Error==1.
char *encx_client_login_with_captcha(long long handle, char *login, char *password, char *magic_numbers);

// PingGame checks engine reachability with the code-send timeout.
char *encx_client_ping_game(long long handle, long long game_id);

// RejectTeamInvitation rejects a team invitation.
char *encx_client_reject_team_invitation(long long handle, long long team_id);

// RemoveTeamInvitation removes a pending invitation sent by a team.
char *encx_client_remove_team_invitation(long long handle, long long team_id, long long user_id);

// RenameTeam renames a team.
char *encx_client_rename_team(long long handle, long long team_id, char *name);

// RequestTeamMembership sends a request to join a team by name.
char *encx_client_request_team_membership(long long handle, char *team_name);

// SendBonusCode submits a bonus answer via BonusAction.Answer. Returns updated GameModel JSON.
char *encx_client_send_bonus_code(long long handle, long long game_id, long long level_id, long long level_number, char *code);

// SendCode submits an answer via LevelAction.Answer. Returns updated GameModel JSON.
char *encx_client_send_code(long long handle, long long game_id, long long level_id, long long level_number, char *code);

// SetCodeSendTimeoutSeconds sets the per-request timeout for code submissions and quick probes.
// Zero or negative values reset to the default (1 second).
char *encx_client_set_code_send_timeout_seconds(long long handle, long long seconds);

// SetEngine selects the Encounter backend: "legacy" (default), "new", or
// "auto" to probe the API host once. Unknown values are ignored so a caller
// cannot silently end up on the wrong engine.
//
// Encounter is migrating from the ASP.NET engine to a REST one; both are
// implemented, and every method of this client works the same on either.
char *encx_client_set_engine(long long handle, char *mode);

// SetGameRequestMinIntervalMillis sets the minimum interval between mobile game-engine requests.
// Zero or negative values disable pacing.
char *encx_client_set_game_request_min_interval_millis(long long handle, long long milliseconds);

// SetHARRecordingEnabled toggles HAR 1.2 capture for Encounter HTTP traffic.
char *encx_client_set_har_recording_enabled(long long handle, int enabled);

// SetTeamForum updates the team external forum URL.
char *encx_client_set_team_forum(long long handle, long long team_id, char *forum);

// SetTeamSite updates the team website URL.
char *encx_client_set_team_site(long long handle, long long team_id, char *site);

// EventText returns a human-readable game event status description.
char *encx_event_text(long long code);

// LoginErrorText returns a human-readable login error description.
char *encx_login_error_text(long long code);

// ParseTeamInvitations extracts incoming team invitations from HTML. Returns JSON array.
char *encx_parse_team_invitations(char *html);

// ParseTeamLinks extracts team IDs and names from HTML. Returns JSON array of TeamInfo.
char *encx_parse_team_links(char *html);

// ParseTeamManagementInfo extracts team management info from HTML. Returns JSON.
char *encx_parse_team_management_info(char *html, long long team_id);
