// Code generated by encxphpgen. DO NOT EDIT.

package main

/*
#include <stdlib.h>
*/
import "C"

import (
	"github.com/skrashevich/encx-cli/bindings/php/internal/rt"
	"github.com/skrashevich/encx-cli/mobile/encxmobile"
)

// AcceptTeamInvitation accepts a team invitation.
//
//export encx_client_accept_team_invitation
func encx_client_accept_team_invitation(handle C.longlong, team_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.AcceptTeamInvitation(int64(team_id)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// AdminCreateGame creates a game and returns its id. paramsJSON must decode
// into encx.AdminCreateGameParams (title, description, game_type,
// start_datetime, finish_datetime, ...).
//
//export encx_client_admin_create_game
func encx_client_admin_create_game(handle C.longlong, params_json *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.AdminCreateGame(C.GoString(params_json))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// APIBaseURL returns the host the new engine is reached at.
//
//export encx_client_api_base_url
func encx_client_api_base_url(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(client.APIBaseURL()))
}

// ClearHAR removes all captured HAR entries.
//
//export encx_client_clear_har
func encx_client_clear_har(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	client.ClearHAR()
	return cEnvelope(rt.OKVoid())
}

// ClearHARFirst removes the n oldest captured HAR entries.
//
//export encx_client_clear_har_first
func encx_client_clear_har_first(handle C.longlong, n C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	client.ClearHARFirst(int64(n))
	return cEnvelope(rt.OKVoid())
}

// Domain returns the configured Encounter domain.
//
//export encx_client_domain
func encx_client_domain(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(client.Domain()))
}

// Engine reports which backend is actually serving this client.
//
//export encx_client_engine
func encx_client_engine(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(client.Engine()))
}

// EnterGame registers the player in a game. Returns raw server response.
//
//export encx_client_enter_game
func encx_client_enter_game(handle C.longlong, game_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.EnterGame(int64(game_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// ExportCookies serializes session cookies to JSON bytes for persistent storage.
//
//export encx_client_export_cookies
func encx_client_export_cookies(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.ExportCookies()
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// ExportHAR returns captured traffic as a HAR 1.2 JSON document.
//
//export encx_client_export_har
func encx_client_export_har(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.ExportHAR()
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// ExportHARSnapshot atomically exports captured traffic together with its
// entry count; pass the count to ClearHARFirst after a successful upload so
// entries captured during the upload are preserved.
//
//export encx_client_export_har_snapshot
func encx_client_export_har_snapshot(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.ExportHARSnapshot()
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetDomainGames returns games parsed from the domain main page as JSON array.
//
//export encx_client_get_domain_games
func encx_client_get_domain_games(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetDomainGames()
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetGameDetails returns the game details page HTML.
//
//export encx_client_get_game_details
func encx_client_get_game_details(handle C.longlong, game_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetGameDetails(int64(game_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetGameList returns ComingGames and ActiveGames as JSON. page is 1-based (0 = first page).
//
//export encx_client_get_game_list
func encx_client_get_game_list(handle C.longlong, page C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetGameList(int64(page))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetGameModel returns the current game state as GameModel JSON.
//
//export encx_client_get_game_model
func encx_client_get_game_model(handle C.longlong, game_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetGameModel(int64(game_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetGameModelLevel returns the state for a specific level number in storm sequence games.
//
//export encx_client_get_game_model_level
func encx_client_get_game_model_level(handle C.longlong, game_id C.longlong, level_number C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetGameModelLevel(int64(game_id), int64(level_number))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetGameStatistics returns full game statistics as JSON.
//
//export encx_client_get_game_statistics
func encx_client_get_game_statistics(handle C.longlong, game_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetGameStatistics(int64(game_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetMyTeamDetails returns the current user's team page HTML.
//
//export encx_client_get_my_team_details
func encx_client_get_my_team_details(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetMyTeamDetails()
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetPenaltyHint requests a penalty hint. Returns updated GameModel JSON.
//
//export encx_client_get_penalty_hint
func encx_client_get_penalty_hint(handle C.longlong, game_id C.longlong, penalty_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetPenaltyHint(int64(game_id), int64(penalty_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetProfile returns the current user profile as JSON.
//
//export encx_client_get_profile
func encx_client_get_profile(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetProfile()
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetTeamDetails returns team details page HTML.
//
//export encx_client_get_team_details
func encx_client_get_team_details(handle C.longlong, team_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetTeamDetails(int64(team_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetTeamInvitations returns team invitations addressed to the current user as JSON.
//
//export encx_client_get_team_invitations
func encx_client_get_team_invitations(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetTeamInvitations()
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetTeamManagementInfo returns parsed team management info as JSON.
//
//export encx_client_get_team_management_info
func encx_client_get_team_management_info(handle C.longlong, team_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetTeamManagementInfo(int64(team_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// GetTimeoutToGame returns seconds until game start, or -1 if no counter is present.
//
//export encx_client_get_timeout_to_game
func encx_client_get_timeout_to_game(handle C.longlong, game_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.GetTimeoutToGame(int64(game_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// HAREntryCount returns the number of captured HAR entries.
//
//export encx_client_har_entry_count
func encx_client_har_entry_count(handle C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(client.HAREntryCount()))
}

// ImportCookies restores session cookies from JSON bytes produced by ExportCookies.
//
//export encx_client_import_cookies
func encx_client_import_cookies(handle C.longlong, data *C.char, data_len C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.ImportCookies(cBytes(data, data_len)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// InviteTeamMember invites a user login into a team.
//
//export encx_client_invite_team_member
func encx_client_invite_team_member(handle C.longlong, team_id C.longlong, login *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.InviteTeamMember(int64(team_id), C.GoString(login)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// LeaveTeam leaves a team when TeamDetails.aspx exposes a leave action.
//
//export encx_client_leave_team
func encx_client_leave_team(handle C.longlong, team_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.LeaveTeam(int64(team_id)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// Login authenticates on the Encounter domain. Returns LoginResponse JSON.
//
//export encx_client_login
func encx_client_login(handle C.longlong, login *C.char, password *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.Login(C.GoString(login), C.GoString(password))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// LoginWithCaptcha authenticates with CAPTCHA digits when Login returns Error==1.
//
//export encx_client_login_with_captcha
func encx_client_login_with_captcha(handle C.longlong, login *C.char, password *C.char, magic_numbers *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.LoginWithCaptcha(C.GoString(login), C.GoString(password), C.GoString(magic_numbers))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// PingGame checks engine reachability with the code-send timeout.
//
//export encx_client_ping_game
func encx_client_ping_game(handle C.longlong, game_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.PingGame(int64(game_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// RejectTeamInvitation rejects a team invitation.
//
//export encx_client_reject_team_invitation
func encx_client_reject_team_invitation(handle C.longlong, team_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.RejectTeamInvitation(int64(team_id)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// RemoveTeamInvitation removes a pending invitation sent by a team.
//
//export encx_client_remove_team_invitation
func encx_client_remove_team_invitation(handle C.longlong, team_id C.longlong, user_id C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.RemoveTeamInvitation(int64(team_id), int64(user_id)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// RenameTeam renames a team.
//
//export encx_client_rename_team
func encx_client_rename_team(handle C.longlong, team_id C.longlong, name *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.RenameTeam(int64(team_id), C.GoString(name)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// RequestTeamMembership sends a request to join a team by name.
//
//export encx_client_request_team_membership
func encx_client_request_team_membership(handle C.longlong, team_name *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.RequestTeamMembership(C.GoString(team_name)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// SendBonusCode submits a bonus answer via BonusAction.Answer. Returns updated GameModel JSON.
//
//export encx_client_send_bonus_code
func encx_client_send_bonus_code(handle C.longlong, game_id C.longlong, level_id C.longlong, level_number C.longlong, code *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.SendBonusCode(int64(game_id), int64(level_id), int64(level_number), C.GoString(code))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// SendCode submits an answer via LevelAction.Answer. Returns updated GameModel JSON.
//
//export encx_client_send_code
func encx_client_send_code(handle C.longlong, game_id C.longlong, level_id C.longlong, level_number C.longlong, code *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	value, err := client.SendCode(int64(game_id), int64(level_id), int64(level_number), C.GoString(code))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// SetCodeSendTimeoutSeconds sets the per-request timeout for code submissions and quick probes.
// Zero or negative values reset to the default (1 second).
//
//export encx_client_set_code_send_timeout_seconds
func encx_client_set_code_send_timeout_seconds(handle C.longlong, seconds C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	client.SetCodeSendTimeoutSeconds(int64(seconds))
	return cEnvelope(rt.OKVoid())
}

// SetEngine selects the Encounter backend: "legacy" (default), "new", or
// "auto" to probe the API host once. Unknown values are ignored so a caller
// cannot silently end up on the wrong engine.
//
// Encounter is migrating from the ASP.NET engine to a REST one; both are
// implemented, and every method of this client works the same on either.
//
//export encx_client_set_engine
func encx_client_set_engine(handle C.longlong, mode *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	client.SetEngine(C.GoString(mode))
	return cEnvelope(rt.OKVoid())
}

// SetGameRequestMinIntervalMillis sets the minimum interval between mobile game-engine requests.
// Zero or negative values disable pacing.
//
//export encx_client_set_game_request_min_interval_millis
func encx_client_set_game_request_min_interval_millis(handle C.longlong, milliseconds C.longlong) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	client.SetGameRequestMinIntervalMillis(int64(milliseconds))
	return cEnvelope(rt.OKVoid())
}

// SetHARRecordingEnabled toggles HAR 1.2 capture for Encounter HTTP traffic.
//
//export encx_client_set_har_recording_enabled
func encx_client_set_har_recording_enabled(handle C.longlong, enabled C.int) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	client.SetHARRecordingEnabled(enabled != 0)
	return cEnvelope(rt.OKVoid())
}

// SetTeamForum updates the team external forum URL.
//
//export encx_client_set_team_forum
func encx_client_set_team_forum(handle C.longlong, team_id C.longlong, forum *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.SetTeamForum(int64(team_id), C.GoString(forum)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// SetTeamSite updates the team website URL.
//
//export encx_client_set_team_site
func encx_client_set_team_site(handle C.longlong, team_id C.longlong, site *C.char) *C.char {
	client, err := rt.Default.Get(int64(handle))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	if err = client.SetTeamSite(int64(team_id), C.GoString(site)); err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OKVoid())
}

// EventText returns a human-readable game event status description.
//
//export encx_event_text
func encx_event_text(code C.longlong) *C.char {
	return cEnvelope(rt.OK(encxmobile.EventText(int64(code))))
}

// LoginErrorText returns a human-readable login error description.
//
//export encx_login_error_text
func encx_login_error_text(code C.longlong) *C.char {
	return cEnvelope(rt.OK(encxmobile.LoginErrorText(int64(code))))
}

// NewClient creates an Encounter API client for the given domain.
// Set insecureTLS to true to skip TLS certificate verification (e.g. for tech.en.cx).
//
//export encx_new_client
func encx_new_client(domain *C.char, insecure_tls C.int) *C.char {
	handle, err := rt.Default.Add(encxmobile.NewClient(C.GoString(domain), insecure_tls != 0))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(handle))
}

// NewClientWithOptions creates a client with extended configuration.
// timeoutSeconds: HTTP client timeout (0 = default 15s). lang: API language (empty = "ru").
//
//export encx_new_client_with_options
func encx_new_client_with_options(domain *C.char, insecure_tls C.int, use_http C.int, timeout_seconds C.longlong, lang *C.char) *C.char {
	handle, err := rt.Default.Add(encxmobile.NewClientWithOptions(C.GoString(domain), insecure_tls != 0, use_http != 0, int64(timeout_seconds), C.GoString(lang)))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(handle))
}

// ParseTeamInvitations extracts incoming team invitations from HTML. Returns JSON array.
//
//export encx_parse_team_invitations
func encx_parse_team_invitations(html *C.char) *C.char {
	value, err := encxmobile.ParseTeamInvitations(C.GoString(html))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// ParseTeamLinks extracts team IDs and names from HTML. Returns JSON array of TeamInfo.
//
//export encx_parse_team_links
func encx_parse_team_links(html *C.char) *C.char {
	value, err := encxmobile.ParseTeamLinks(C.GoString(html))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}

// ParseTeamManagementInfo extracts team management info from HTML. Returns JSON.
//
//export encx_parse_team_management_info
func encx_parse_team_management_info(html *C.char, team_id C.longlong) *C.char {
	value, err := encxmobile.ParseTeamManagementInfo(C.GoString(html), int64(team_id))
	if err != nil {
		return cEnvelope(rt.Fail(err))
	}
	return cEnvelope(rt.OK(value))
}
