<?php

// Code generated by encxphpgen. DO NOT EDIT.

declare(strict_types=1);

namespace Encx;

/**
 * A live Encounter client backed by the encx shared library.
 *
 * An instance owns one handle into the Go side, so it is created through the
 * static factories below rather than with new. Release it with close() when the
 * work is done; the destructor does the same for a client that outlives its
 * last use.
 */
final class Client
{
    /** The live handle into the Go client registry, or null once closed. */
    private ?int $handle;

    private function __construct(int $handle)
    {
        $this->handle = $handle;
    }

    /**
     * Frees the Go client for an instance that was never closed explicitly.
     *
     * A destructor must not let anything escape, since PHP turns that into a
     * fatal error during shutdown; every failure here is therefore swallowed.
     * \Throwable and not EncxException, because FFI reports a broken binding
     * as \FFI\Exception, which extends \Error and so is not an exception at
     * all. Call close() instead when the outcome matters.
     *
     * PHP forbids a return type on __destruct, so this signature has none.
     */
    public function __destruct()
    {
        try {
            $this->close();
        } catch (\Throwable) {
            // Nothing left to report once the object is being destroyed.
        }
    }

    /**
     * Releases the Go client behind this instance.
     *
     * The handle is cleared before the call, so a second close() — including
     * the one from the destructor — does nothing and frees nothing twice.
     *
     * @throws EncxException
     */
    public function close(): void
    {
        $handle = $this->handle;
        if ($handle === null) {
            return;
        }

        $this->handle = null;
        Ffi::call('encx_client_free', [$handle]);
    }

    /**
     * Returns the handle this instance still owns.
     *
     * @throws EncxException when the client has already been closed
     */
    private function handle(): int
    {
        if ($this->handle === null) {
            throw new EncxException('the encx client is closed');
        }

        return $this->handle;
    }

    /**
     * NewClient creates an Encounter API client for the given domain.
     * Set insecureTLS to true to skip TLS certificate verification (e.g. for tech.en.cx).
     *
     * @throws EncxException
     */
    public static function newClient(string $domain, bool $insecureTLS): self
    {
        return new self((int) Ffi::call('encx_new_client', [$domain, $insecureTLS ? 1 : 0]));
    }

    /**
     * NewClientWithOptions creates a client with extended configuration.
     * timeoutSeconds: HTTP client timeout (0 = default 15s). lang: API language (empty = "ru").
     *
     * @throws EncxException
     */
    public static function newClientWithOptions(
        string $domain,
        bool $insecureTLS,
        bool $useHTTP,
        int $timeoutSeconds,
        string $lang,
    ): self {
        return new self((int) Ffi::call('encx_new_client_with_options', [
            $domain,
            $insecureTLS ? 1 : 0,
            $useHTTP ? 1 : 0,
            $timeoutSeconds,
            $lang,
        ]));
    }

    /**
     * AcceptTeamInvitation accepts a team invitation.
     *
     * @throws EncxException
     */
    public function acceptTeamInvitation(int $teamID): void
    {
        Ffi::call('encx_client_accept_team_invitation', [$this->handle(), $teamID]);
    }

    /**
     * APIBaseURL returns the host the new engine is reached at.
     *
     * @throws EncxException
     */
    public function apiBaseURL(): string
    {
        return (string) Ffi::call('encx_client_api_base_url', [$this->handle()]);
    }

    /**
     * ClearHAR removes all captured HAR entries.
     *
     * @throws EncxException
     */
    public function clearHAR(): void
    {
        Ffi::call('encx_client_clear_har', [$this->handle()]);
    }

    /**
     * ClearHARFirst removes the n oldest captured HAR entries.
     *
     * @throws EncxException
     */
    public function clearHARFirst(int $n): void
    {
        Ffi::call('encx_client_clear_har_first', [$this->handle(), $n]);
    }

    /**
     * Domain returns the configured Encounter domain.
     *
     * @throws EncxException
     */
    public function domain(): string
    {
        return (string) Ffi::call('encx_client_domain', [$this->handle()]);
    }

    /**
     * Engine reports which backend is actually serving this client.
     *
     * @throws EncxException
     */
    public function engine(): string
    {
        return (string) Ffi::call('encx_client_engine', [$this->handle()]);
    }

    /**
     * EnterGame registers the player in a game. Returns raw server response.
     *
     * @throws EncxException
     */
    public function enterGame(int $gameID): string
    {
        return (string) Ffi::call('encx_client_enter_game', [$this->handle(), $gameID]);
    }

    /**
     * ExportCookies serializes session cookies to JSON bytes for persistent storage.
     *
     * @throws EncxException
     */
    public function exportCookies(): string
    {
        return Ffi::decodeBytes(Ffi::call('encx_client_export_cookies', [$this->handle()]));
    }

    /**
     * ExportHAR returns captured traffic as a HAR 1.2 JSON document.
     *
     * @throws EncxException
     */
    public function exportHAR(): string
    {
        return (string) Ffi::call('encx_client_export_har', [$this->handle()]);
    }

    /**
     * ExportHARSnapshot atomically exports captured traffic together with its
     * entry count; pass the count to ClearHARFirst after a successful upload so
     * entries captured during the upload are preserved.
     *
     * @return array{JSON: string, EntryCount: int}
     * @throws EncxException
     */
    public function exportHARSnapshot(): array
    {
        return (array) Ffi::call('encx_client_export_har_snapshot', [$this->handle()]);
    }

    /**
     * GetDomainGames returns games parsed from the domain main page as JSON array.
     *
     * @throws EncxException
     */
    public function getDomainGames(): string
    {
        return (string) Ffi::call('encx_client_get_domain_games', [$this->handle()]);
    }

    /**
     * GetGameDetails returns the game details page HTML.
     *
     * @throws EncxException
     */
    public function getGameDetails(int $gameID): string
    {
        return (string) Ffi::call('encx_client_get_game_details', [$this->handle(), $gameID]);
    }

    /**
     * GetGameList returns ComingGames and ActiveGames as JSON. page is 1-based (0 = first page).
     *
     * @throws EncxException
     */
    public function getGameList(int $page): string
    {
        return (string) Ffi::call('encx_client_get_game_list', [$this->handle(), $page]);
    }

    /**
     * GetGameModel returns the current game state as GameModel JSON.
     *
     * @throws EncxException
     */
    public function getGameModel(int $gameID): string
    {
        return (string) Ffi::call('encx_client_get_game_model', [$this->handle(), $gameID]);
    }

    /**
     * GetGameModelLevel returns the state for a specific level number in storm sequence games.
     *
     * @throws EncxException
     */
    public function getGameModelLevel(int $gameID, int $levelNumber): string
    {
        return (string) Ffi::call('encx_client_get_game_model_level', [
            $this->handle(),
            $gameID,
            $levelNumber,
        ]);
    }

    /**
     * GetGameStatistics returns full game statistics as JSON.
     *
     * @throws EncxException
     */
    public function getGameStatistics(int $gameID): string
    {
        return (string) Ffi::call('encx_client_get_game_statistics', [$this->handle(), $gameID]);
    }

    /**
     * GetMyTeamDetails returns the current user's team page HTML.
     *
     * @throws EncxException
     */
    public function getMyTeamDetails(): string
    {
        return (string) Ffi::call('encx_client_get_my_team_details', [$this->handle()]);
    }

    /**
     * GetPenaltyHint requests a penalty hint. Returns updated GameModel JSON.
     *
     * @throws EncxException
     */
    public function getPenaltyHint(int $gameID, int $penaltyID): string
    {
        return (string) Ffi::call('encx_client_get_penalty_hint', [
            $this->handle(),
            $gameID,
            $penaltyID,
        ]);
    }

    /**
     * GetProfile returns the current user profile as JSON.
     *
     * @throws EncxException
     */
    public function getProfile(): string
    {
        return (string) Ffi::call('encx_client_get_profile', [$this->handle()]);
    }

    /**
     * GetTeamDetails returns team details page HTML.
     *
     * @throws EncxException
     */
    public function getTeamDetails(int $teamID): string
    {
        return (string) Ffi::call('encx_client_get_team_details', [$this->handle(), $teamID]);
    }

    /**
     * GetTeamInvitations returns team invitations addressed to the current user as JSON.
     *
     * @throws EncxException
     */
    public function getTeamInvitations(): string
    {
        return (string) Ffi::call('encx_client_get_team_invitations', [$this->handle()]);
    }

    /**
     * GetTeamManagementInfo returns parsed team management info as JSON.
     *
     * @throws EncxException
     */
    public function getTeamManagementInfo(int $teamID): string
    {
        return (string) Ffi::call('encx_client_get_team_management_info', [
            $this->handle(),
            $teamID,
        ]);
    }

    /**
     * GetTimeoutToGame returns seconds until game start, or -1 if no counter is present.
     *
     * @throws EncxException
     */
    public function getTimeoutToGame(int $gameID): int
    {
        return (int) Ffi::call('encx_client_get_timeout_to_game', [$this->handle(), $gameID]);
    }

    /**
     * HAREntryCount returns the number of captured HAR entries.
     *
     * @throws EncxException
     */
    public function harEntryCount(): int
    {
        return (int) Ffi::call('encx_client_har_entry_count', [$this->handle()]);
    }

    /**
     * ImportCookies restores session cookies from JSON bytes produced by ExportCookies.
     *
     * @throws EncxException
     */
    public function importCookies(string $data): void
    {
        Ffi::call('encx_client_import_cookies', [$this->handle(), $data, strlen($data)]);
    }

    /**
     * InviteTeamMember invites a user login into a team.
     *
     * @throws EncxException
     */
    public function inviteTeamMember(int $teamID, string $login): void
    {
        Ffi::call('encx_client_invite_team_member', [$this->handle(), $teamID, $login]);
    }

    /**
     * LeaveTeam leaves a team when TeamDetails.aspx exposes a leave action.
     *
     * @throws EncxException
     */
    public function leaveTeam(int $teamID): void
    {
        Ffi::call('encx_client_leave_team', [$this->handle(), $teamID]);
    }

    /**
     * Login authenticates on the Encounter domain. Returns LoginResponse JSON.
     *
     * @throws EncxException
     */
    public function login(string $login, string $password): string
    {
        return (string) Ffi::call('encx_client_login', [$this->handle(), $login, $password]);
    }

    /**
     * LoginWithCaptcha authenticates with CAPTCHA digits when Login returns Error==1.
     *
     * @throws EncxException
     */
    public function loginWithCaptcha(string $login, string $password, string $magicNumbers): string
    {
        return (string) Ffi::call('encx_client_login_with_captcha', [
            $this->handle(),
            $login,
            $password,
            $magicNumbers,
        ]);
    }

    /**
     * PingGame checks engine reachability with the code-send timeout.
     *
     * @throws EncxException
     */
    public function pingGame(int $gameID): string
    {
        return (string) Ffi::call('encx_client_ping_game', [$this->handle(), $gameID]);
    }

    /**
     * RejectTeamInvitation rejects a team invitation.
     *
     * @throws EncxException
     */
    public function rejectTeamInvitation(int $teamID): void
    {
        Ffi::call('encx_client_reject_team_invitation', [$this->handle(), $teamID]);
    }

    /**
     * RemoveTeamInvitation removes a pending invitation sent by a team.
     *
     * @throws EncxException
     */
    public function removeTeamInvitation(int $teamID, int $userID): void
    {
        Ffi::call('encx_client_remove_team_invitation', [$this->handle(), $teamID, $userID]);
    }

    /**
     * RenameTeam renames a team.
     *
     * @throws EncxException
     */
    public function renameTeam(int $teamID, string $name): void
    {
        Ffi::call('encx_client_rename_team', [$this->handle(), $teamID, $name]);
    }

    /**
     * RequestTeamMembership sends a request to join a team by name.
     *
     * @throws EncxException
     */
    public function requestTeamMembership(string $teamName): void
    {
        Ffi::call('encx_client_request_team_membership', [$this->handle(), $teamName]);
    }

    /**
     * SendBonusCode submits a bonus answer via BonusAction.Answer. Returns updated GameModel JSON.
     *
     * @throws EncxException
     */
    public function sendBonusCode(int $gameID, int $levelID, int $levelNumber, string $code): string
    {
        return (string) Ffi::call('encx_client_send_bonus_code', [
            $this->handle(),
            $gameID,
            $levelID,
            $levelNumber,
            $code,
        ]);
    }

    /**
     * SendCode submits an answer via LevelAction.Answer. Returns updated GameModel JSON.
     *
     * @throws EncxException
     */
    public function sendCode(int $gameID, int $levelID, int $levelNumber, string $code): string
    {
        return (string) Ffi::call('encx_client_send_code', [
            $this->handle(),
            $gameID,
            $levelID,
            $levelNumber,
            $code,
        ]);
    }

    /**
     * SetCodeSendTimeoutSeconds sets the per-request timeout for code submissions and quick probes.
     * Zero or negative values reset to the default (1 second).
     *
     * @throws EncxException
     */
    public function setCodeSendTimeoutSeconds(int $seconds): void
    {
        Ffi::call('encx_client_set_code_send_timeout_seconds', [$this->handle(), $seconds]);
    }

    /**
     * SetEngine selects the Encounter backend: "legacy" (default), "new", or
     * "auto" to probe the API host once. Unknown values are ignored so a caller
     * cannot silently end up on the wrong engine.
     *
     * Encounter is migrating from the ASP.NET engine to a REST one; both are
     * implemented, and every method of this client works the same on either.
     *
     * @throws EncxException
     */
    public function setEngine(string $mode): void
    {
        Ffi::call('encx_client_set_engine', [$this->handle(), $mode]);
    }

    /**
     * SetGameRequestMinIntervalMillis sets the minimum interval between mobile game-engine requests.
     * Zero or negative values disable pacing.
     *
     * @throws EncxException
     */
    public function setGameRequestMinIntervalMillis(int $milliseconds): void
    {
        Ffi::call('encx_client_set_game_request_min_interval_millis', [
            $this->handle(),
            $milliseconds,
        ]);
    }

    /**
     * SetHARRecordingEnabled toggles HAR 1.2 capture for Encounter HTTP traffic.
     *
     * @throws EncxException
     */
    public function setHARRecordingEnabled(bool $enabled): void
    {
        Ffi::call('encx_client_set_har_recording_enabled', [$this->handle(), $enabled ? 1 : 0]);
    }

    /**
     * SetTeamForum updates the team external forum URL.
     *
     * @throws EncxException
     */
    public function setTeamForum(int $teamID, string $forum): void
    {
        Ffi::call('encx_client_set_team_forum', [$this->handle(), $teamID, $forum]);
    }

    /**
     * SetTeamSite updates the team website URL.
     *
     * @throws EncxException
     */
    public function setTeamSite(int $teamID, string $site): void
    {
        Ffi::call('encx_client_set_team_site', [$this->handle(), $teamID, $site]);
    }
}
