<?php

// Code generated by encxphpgen. DO NOT EDIT.

declare(strict_types=1);

namespace Encx;

/**
 * The encx package-level functions, which need no client and hold no state.
 */
final class Helpers
{
    /**
     * EventText returns a human-readable game event status description.
     *
     * @throws EncxException
     */
    public static function eventText(int $code): string
    {
        return (string) Ffi::call('encx_event_text', [$code]);
    }

    /**
     * LoginErrorText returns a human-readable login error description.
     *
     * @throws EncxException
     */
    public static function loginErrorText(int $code): string
    {
        return (string) Ffi::call('encx_login_error_text', [$code]);
    }

    /**
     * ParseTeamInvitations extracts incoming team invitations from HTML. Returns JSON array.
     *
     * @throws EncxException
     */
    public static function parseTeamInvitations(string $html): string
    {
        return (string) Ffi::call('encx_parse_team_invitations', [$html]);
    }

    /**
     * ParseTeamLinks extracts team IDs and names from HTML. Returns JSON array of TeamInfo.
     *
     * @throws EncxException
     */
    public static function parseTeamLinks(string $html): string
    {
        return (string) Ffi::call('encx_parse_team_links', [$html]);
    }

    /**
     * ParseTeamManagementInfo extracts team management info from HTML. Returns JSON.
     *
     * @throws EncxException
     */
    public static function parseTeamManagementInfo(string $html, int $teamID): string
    {
        return (string) Ffi::call('encx_parse_team_management_info', [$html, $teamID]);
    }
}
